version: '3.8'
services:
  flutter-workspace:
    image: developerswork/flutter
    container_name: flutter_workspace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/home/developer/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
 
